version: '3'
services:
  pg-user:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: mozz
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5566:5432"
    networks:
      - db
    command: -p 5566
    restart: unless-stopped


  user-api:
    image: mozdev/user-service:latest
    container_name: user-api
    ports:
      - "8082:8082"
    depends_on:
      - pg-user
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-user:5432/user


    networks:
      - db


networks:
  db:
    driver: bridge
volumes:
  db:

